name: Build Solution
on: [ push, workflow_call ]
jobs:
  publish_windows:
    name: "Build for Windows"
    runs-on: windows-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Setup .NET Cli"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: "Build Solution"
        run: dotnet build
  
  publish_linux:
    name: "Build for Linux"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Setup AOT Dependencies"
        run: |
          sudo apt update
          sudo apt install clang zlib1g-dev -y
      - name: "Setup .NET Cli"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: "Build Solution"
        run: dotnet build